// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Jane Finch Cannabis",
  domain: "www.janefinchcannabis.ca",
  city: "North York",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-north-york",
  address: "2728 Jane St, North York, ON M3L 2G6",
  streetAddress: "2728 Jane St",
  postalCode: "M3L 2G6",
  phone: "+1 (437) 524-9336",
  phoneIntl: "+14375249336",
  neighborhood: "Jane and Finch / North York",
  nearbyAreas: ["Jane and Finch", "North York", "Jane Street", "Finch Avenue", "York University area", "Black Creek", "Downsview", "Humbermede", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.7432147",
  longitude: "-79.5144564",
  hours: ["Open 24 Hours"],
  seoTitle: "Jane Finch Cannabis | Weed Dispensary in North York",
  metaDescription: "Jane Finch Cannabis is a local weed dispensary in North York offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Jane and Finch", "North York", "Jane Street"],
  introVariant: "Jane Finch Cannabis is a local weed dispensary in North York, located at 2728 Jane St. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Jane and Finch / North York, a cannabis store in North York, or a local weed shop close to North York, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Jane and Finch / North York district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Free plaza parking is available directly in front of the store",
  transitNote: "Easily accessible via local TTC bus routes on Jane Street and Finch Avenue.",
  sectionTitle: "Serving Customers Near Jane and Finch in North York"
};
