import {
  CITY,
  COUNTRY,
  FULL_ADDRESS,
  HOURS_SHORT,
  LATITUDE,
  LONGITUDE,
  PHONE_DISPLAY,
  PHONE_INTL,
  POSTAL_CODE,
  REGION,
  SITE_ORIGIN,
  STORE_NAME,
  STREET_ADDRESS,
} from "./nap";

// Google Business Profile local SEO location configuration (NAP must match schema/footer/contact)
export const gbpLocation = {
  storeName: STORE_NAME,
  domain: SITE_ORIGIN.replace(/^https:\/\//, ""),
  city: CITY,
  province: REGION,
  country: COUNTRY,
  slug: "weed-dispensary-north-york",
  address: FULL_ADDRESS,
  streetAddress: STREET_ADDRESS,
  postalCode: POSTAL_CODE,
  phone: PHONE_DISPLAY,
  phoneIntl: PHONE_INTL,
  neighborhood: "Jane and Finch / North York",
  nearbyAreas: [
    "Jane and Finch",
    "Jane and Sheppard",
    "North York",
    "Jane Street",
    "Finch Avenue",
    "York University area",
    "Black Creek",
    "Downsview",
    "Humbermede",
    "Finch West",
  ],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories",
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: String(LATITUDE),
  longitude: String(LONGITUDE),
  hours: [HOURS_SHORT],
  seoTitle: "North York Weed Dispensary at Jane & Sheppard | Open 24 Hours",
  metaDescription:
    "Walk-in North York weed dispensary at 2728 Jane St, Jane & Sheppard. Jane Finch Cannabis is open 24 hours, 7 days. Plaza parking out front. Call +1 (437) 524-9336. Adults 19+.",
  localLandmarks: ["Jane and Finch", "Jane and Sheppard", "North York", "Jane Street"],
  introVariant:
    "Jane Finch Cannabis is the walk-in weed dispensary at 2728 Jane St, North York, in the Jane and Sheppard / Jane and Finch corridor. We serve adults 19+ looking for cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and accessories. Open 24 hours, 7 days.",
  neighborhoodDescription:
    "The store sits on Jane Street in North York, at the Jane St & Sheppard Ave W area, with plaza parking in front and TTC bus service along Jane Street and nearby Finch Avenue.",
  parkingNote: "Free plaza parking is available directly in front of the store",
  transitNote: "Accessible via local TTC bus routes on Jane Street and Finch Avenue.",
  sectionTitle: "Serving walk-in customers near Jane Finch and Jane & Sheppard",
};
